import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
data = pd.read_excel("Kaggle.xlsx")
data.drop(["State","District"], axis=1, inplace=True)
data["Date"] = pd.to_datetime(data["Date"])
data.head(10)
data.set_index('Date', inplace=True)
print("Weekly Averages")
print(data.resample('w').mean())
print("Monthly Averages")
print(data.resample('m').mean())
print("Yearly Averages")
print(data.resample('y').mean())
print("Weekly Median")
print(data.resample('w').median())
print("Monthly Median")
print(data.resample('m').median())
print("Yearly Median")
print(data.resample('y').median())
plt.scatter(data['Confirmed'],data['Recovered'],color = 'g', s = 5)
plt.show()
plt.scatter(data['Tested'],data['Confirmed'],color = 'r',s = 5)
plt.show()
plt.scatter(data['Confirmed'],data['Deceased'],color = 'y',s = 5)
plt.show()
plt.bar(data['Confirmed'],data['Recovered'],color = 'g', width = 5)
plt.show()
plt.bar(data['Tested'],data['Confirmed'],color = 'r', width = 10)
plt.show()
plt.bar(data['Confirmed'],data['Deceased'],color = 'y', width = 5)
plt.show()
sns.regplot(data['Confirmed'],data['Deceased'],color = 'r')
plt.show()
sns.regplot(data['Tested'],data['Confirmed'],color = 'r')
plt.show()
sns.regplot(data['Confirmed'],data['Deceased'],color = 'y')