import pandas as pd               #Excel Data analyse                                              
import seaborn as sns             #Graph
import matplotlib.pyplot as plt   #Graph
 
data = pd.read_excel("Kaggle.xlsx")          
data.drop(["State","District"], axis=1, inplace=True)
data["Date"] = pd.to_datetime(data["Date"])
data.set_index('Date', inplace=True)
print("-------------------------------------------------------------Weekly Averages-----------------------------------------------")
print(data.resample('w').mean().to_string())
print("-------------------------------------------------------------Monthly Averages----------------------------------------------")
print(data.resample('m').mean().to_string())
print("-------------------------------------------------------------Yearly Averages------------------------------------------------")
print(data.resample('y').mean().to_string())
print("-------------------------------------------------------------Weekly Median----------------------------------------------------")
print(data.resample('w').median().to_string())
print("-------------------------------------------------------------Monthly Median----------------------------------------------------")
print(data.resample('m').median().to_string())
print("-------------------------------------------------------------Yearly Median-----------------------------------------------------")
print(data.resample('y').median().to_string())


plt.scatter(data['Confirmed'],data['Recovered'])
plt.title("Scatter plot of number of confirmed cases Vs Number of recovered cases")
plt.show()
plt.bar(data['Confirmed'],data['Recovered'],color = 'g', width = 5)
plt.title("Bar Graph of number of confirmed cases Vs Number of recovered cases")
plt.show()
sns.regplot(data['Confirmed'],data['Recovered'],color = 'r')
plt.title("Regression line of number of confirmed cases Vs Number of recovered cases")
plt.show()
plt.scatter(data['Tested'],data['Confirmed'])
plt.title("Scatter plot of number of tested cases Vs confirmed Cases ")
plt.show()
plt.bar(data['Tested'],data['Confirmed'],color = 'r', width = 10)
plt.title("Bar Graph of number of tested cases  Vs confirmed Cases ")
plt.show()
sns.regplot(data['Tested'],data['Confirmed'],color = 'r')
plt.title("Regression line of number of tested cases Vs confirmed Cases ")
plt.show()
plt.scatter(data['Confirmed'],data['Deceased'])
plt.title("Scatter plot of number of confirmed cases Vs deceased Case ")
plt.show()
plt.bar(data['Confirmed'],data['Deceased'],color = 'r', width = 10)
plt.title("Bar Graph of number of Confirmed cases  Vs Deceased Cases ")
plt.show()
sns.regplot(data['Confirmed'],data['Deceased'],color = 'y')
plt.title("Regression line of number of confirmed cases Vs deceased Cases ")
plt.show()